spring:
  application:
    name: congif-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saurmaurya/opd-microservices-config.git
          clone-on-start: true
server:
  port: 8888
