spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@opd.caadc.mongodb.net/OPD?retryWrites=true&w=majority

server:
  port: 8081

admin-service:
  app:
    jwtSecret: mycustomsecretkey
    jwtExpirationMs: 86400000
    adminRegSecret: somethingsmart
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    ip-address: ${EUREKA_IP:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
