spring:
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  application:
    name: patient-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@opd.caadc.mongodb.net/OPD?retryWrites=true&w=majority

server:
  port: 8084


admin-service:
  app:
    jwtSecret: mycustomsecretkey
    jwtExpirationMs: 86400000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    ip-address: ${EUREKA_IP:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
