spring:
  application:
    name: appointment-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@opd.caadc.mongodb.net/OPD?retryWrites=true&w=majority
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
server:
  port: 8085
appointment-service:
  app:
    jwtSecret: mycustomsecretkey
    jwtExpirationMs: 86400000
eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    ip-address: ${EUREKA_IP:localhost}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}